import { DUCKDB_TYPE } from "@ggpwnkthx/libduckdb/enums";

const handled = [
  DUCKDB_TYPE.DUCKDB_TYPE_BOOLEAN,
  DUCKDB_TYPE.DUCKDB_TYPE_TINYINT,
  DUCKDB_TYPE.DUCKDB_TYPE_SMALLINT,
  DUCKDB_TYPE.DUCKDB_TYPE_INTEGER,
  DUCKDB_TYPE.DUCKDB_TYPE_BIGINT,
  DUCKDB_TYPE.DUCKDB_TYPE_FLOAT,
  DUCKDB_TYPE.DUCKDB_TYPE_DOUBLE,
  DUCKDB_TYPE.DUCKDB_TYPE_HUGEINT,
  DUCKDB_TYPE.DUCKDB_TYPE_UTINYINT,
  DUCKDB_TYPE.DUCKDB_TYPE_USMALLINT,
  DUCKDB_TYPE.DUCKDB_TYPE_UINTEGER,
  DUCKDB_TYPE.DUCKDB_TYPE_UBIGINT,
  DUCKDB_TYPE.DUCKDB_TYPE_UHUGEINT,
  DUCKDB_TYPE.DUCKDB_TYPE_DATE,
  DUCKDB_TYPE.DUCKDB_TYPE_TIME,
  DUCKDB_TYPE.DUCKDB_TYPE_TIMESTAMP,
  DUCKDB_TYPE.DUCKDB_TYPE_TIMESTAMP_S,
  DUCKDB_TYPE.DUCKDB_TYPE_TIMESTAMP_MS,
  DUCKDB_TYPE.DUCKDB_TYPE_TIMESTAMP_NS,
  DUCKDB_TYPE.DUCKDB_TYPE_INTERVAL,
  DUCKDB_TYPE.DUCKDB_TYPE_VARCHAR,
  DUCKDB_TYPE.DUCKDB_TYPE_BLOB,
];

const allTypes = Object.values(DUCKDB_TYPE).filter((v) => typeof v === "number");
const unhandled = allTypes.filter((t) => !handled.includes(t));
console.log(
  "Unhandled types:",
  unhandled.map((t) => [t, Object.entries(DUCKDB_TYPE).find(([, v]) => v === t)?.[0]]),
);
